# Generated by Django 3.1.7 on 2021-05-06 02:52

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Cust_UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Username', models.CharField(max_length=65, unique=True)),
                ('Password', models.CharField(max_length=128)),
                ('Total_Accounts', models.IntegerField(default=1, null=True)),
                ('isAdmin', models.CharField(default='False', max_length=5)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('Account_Number', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Account_Type', models.CharField(choices=[('Checking', 'Checking Account'), ('Savings', 'Savings Account')], max_length=8)),
                ('Balance', models.FloatField()),
                ('status', models.CharField(choices=[('Active', 'Active Account'), ('Inactive', 'Account is not Active')], default='Inactive', max_length=10)),
                ('Customer_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('Admin_UUID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Password', models.CharField(default='test', max_length=128)),
                ('Username', models.CharField(max_length=65, unique=True)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=200)),
                ('Last_Name', models.CharField(max_length=200)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Username', models.CharField(max_length=65, unique=True)),
                ('Password', models.CharField(max_length=128)),
                ('Total_Accounts', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Acc_Number', models.UUIDField()),
                ('Account_Type', models.CharField(choices=[('Checking', 'Checking Account'), ('Savings', 'Savings Account')], max_length=8)),
                ('Transaction_Type', models.CharField(choices=[('Withdrawal', 'Amount Withdrawn'), ('Deposit', 'Amount Deposited'), ('Send', ' Amount Sent'), ('Receive', 'Amount Received'), ('Transfer', 'Amount Transferred'), ('Refund', 'Refund from Admin'), ('Fees', 'Fees from Admin')], max_length=10)),
                ('Amount', models.FloatField()),
                ('Details', models.CharField(blank=True, max_length=250)),
                ('Transaction_Date', models.DateTimeField(auto_now_add=True)),
                ('Account_Number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.account')),
            ],
            options={
                'ordering': ['Transaction_Date'],
            },
        ),
    ]
