export const RESET_ERROR_MESSAGE = 'RESET_ERROR_MESSAGE'

export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const REQUEST_LOGIN_SUCCESS = 'REQUEST_LOGIN_SUCCESS'
export const REQUEST_LOGIN_FAILURE = 'REQUEST_LOGIN_FAILURE'

export const REQUEST_LOGOUT = 'REQUEST_LOGOUT'
export const REQUEST_LOGOUT_SUCCESS = 'REQUEST_LOGOUT_SUCCESS'

export const REQUEST_ACCOUNTS = 'REQUEST_ACCOUNTS'
export const RECEIVE_ACCOUNTS = 'RECEIVE_ACCOUNTS'
export const REQUEST_ACCOUNTS_FAILURE = 'REQUEST_ACCOUNTS_FAILURE'


export const REQUEST_CUSTOMER = 'REQUEST_CUSTOMER'
export const RECEIVE_CUSTOMER = 'RECEIVE_CUSTOMER'
export const REQUEST_CUSTOMER_FAILURE = 'REQUEST_CUSTOMER_FAILURE'

export const REQUEST_CUSTOMERS = 'REQUEST_CUSTOMERS'
export const RECEIVE_CUSTOMERS = 'RECEIVE_CUSTOMERS'
export const REQUEST_CUSTOMERS_FAILURE = 'REQUEST_CUSTOMERS_FAILURE'

export const REQUEST_INACTIVE_ACCOUNT = 'REQUEST_INACTIVE_ACCOUNT'
export const RECEIVE_INACTIVE_ACCOUNT = 'RECEIVE_INACTIVE_ACCOUNT'
export const REQUEST_INACTIVE_ACCOUNT_FAILURE = 'REQUEST_INACTIVE_ACCOUNT_FAILURE'

export const REQUEST_ACTIVE_ACCOUNT = 'REQUEST_ACTIVE_ACCOUNT'
export const RECEIVE_ACTIVE_ACCOUNT = 'RECEIVE_ACTIVE_ACCOUNT'
export const REQUEST_ACTIVE_ACCOUNT_FAILURE = 'REQUEST_ACTIVE_ACCOUNT_FAILURE'

export const REQUEST_TRANSACTIONS = 'REQUEST_TRANSACTIONS'
export const RECEIVE_TRANSACTIONS = 'RECEIVE_TRANSACTIONS'
export const REQUEST_TRANSACTIONS_FAILURE = 'REQUEST_TRANSACTIONS_FAILURE '

//Add customer
export const CREATE_CUSTOMER_REQUEST = 'CREATE_CUSTOMER_REQUEST'
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS'
export const CREATE_CUSTOMER_FAILED = 'CREATE_CUSTOMER_FAILED'

//Add account
export const CREATE_ACCOUNT_REQUEST = 'CREATE_ACCOUNT_REQUEST'
export const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS'
export const CREATE_ACCOUNT_FAILED = 'CREATE_ACCOUNT_FAILED'


export const ACTIVATE_ACCOUNT = 'ACTIVATE_ACCOUNT'
export const ACTIVATE_ACCOUNT_SUCCESS = 'ACTIVATE_ACCOUNT_SUCCESS'
export const ACTIVATE_ACCOUNT_FAILED = 'ACTIVATE_ACCOUNT_FAILED'

export const DEACTIVATE_ACCOUNT = 'DEACTIVATE_ACCOUNT'
export const DEACTIVATE_ACCOUNT_SUCCESS = 'DEACTIVATE_ACCOUNT_SUCCESS'
export const DEACTIVATE_ACCOUNT_FAILED = 'DEACTIVATE_ACCOUNT_FAILED'

export const REFUND_ACCOUNT = 'REFUND_ACCOUNT'
export const REFUND_ACCOUNT_SUCCESS = 'REFUND_ACCOUNT_SUCCESS'
export const REFUND_ACCOUNT_FAILED = 'REFUND_ACCOUNT_FAILED'

export const TRANSFER_ACCOUNT = 'TRANSFER_ACCOUNT'
export const TRANSFER_ACCOUNT_SUCCESS = 'TRANSFER_ACCOUNT_SUCCESS'
export const TRANSFER_ACCOUNT_FAILED = 'TRANSFER_ACCOUNT_FAILED'

export const EXT_TRANSFER_ACCOUNT = 'EXT_TRANSFER_ACCOUNT'
export const EXT_TRANSFER_ACCOUNT_SUCCESS = 'EXT_TRANSFER_ACCOUNT_SUCCESS'
export const EXT_TRANSFER_ACCOUNT_FAILED = 'EXT_TRANSFER_ACCOUNT_FAILED'